# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY NFLscore.c .
# Compile the C program
RUN gcc -o NFLscore NFLscore.c
# Set the command to run when the container starts
CMD ["./NFLscore"]
